### ISSUE TITLE
Can you update your project?

### ISSUE THREAD

**Issue by billsliu** [danijelh/aspnetcore-vue-typescript-template#16]
This project can't run with dotnet core 3.0, can you update it in order to run with dotnet core 3.0 and above.

**Comment by danijelh** [comment]
Sure, will update with the latest framework version, .NET Core 3.1

**Comment by danijelh** [comment]
@billsliu , **.NET Core 3** and updated **package.json** and **webpack.config.js** has been pushed to the development branch. Final release will follow. If you don't want to wait, you can check it out now.
