### ISSUE TITLE
Core 3.1 Please?

### ISSUE THREAD

**Issue by Grandizer** [danijelh/aspnetcore-vue-typescript-template#22]
Hi there, I was wondering if you could create the following:

ASP.Net Core 3.1
Vue.js (latest)
HMR
WebPack
Razor Pages/MVC (either is fine)
SCSS support

I have been having so much trouble just getting one of the many "attempts" out there to work and not be all about the SPA.

Thanks

**Comment by danijelh** [comment]
Hello @Grandizer, .NET Core 3 and updated package.json and webpack config has been pushed to development branch. 

Final release will follow. If you don't want to wait, you can check it out now. It contains most of the features you mentioned.
