### ISSUE TITLE
 Not Found: har-validator@5.1.2

### ISSUE THREAD

**Issue by martea** [danijelh/aspnetcore-vue-typescript-template#3]
npm verb stack Error: 404 Not Found: har-validator@5.1.2
npm verb stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
npm verb stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm verb stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm verb stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:694:18)
npm verb stack     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
npm verb stack     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
npm verb stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm verb stack     at processImmediate (timers.js:632:19)
npm verb cwd C:\dev\Playground\Web.VueTs\Web.VueTs
npm verb Windows_NT 10.0.17763
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose"
npm verb node v11.8.0
npm verb npm  v6.5.0
npm ERR! code E404
npm ERR! 404 Not Found: har-validator@5.1.2
npm verb exit [ 1, true ]

**Comment by danijelh** [comment]
Can confirm that this is indeed an issue. 

You can solve it for now by invoking the following command
`npm install --save har-validator`

This issue has been reported here https://github.com/request/request/issues/3054. It seems that someone removed that exact version.

I will ship a fix later today or tomorrow.

**Comment by danijelh** [comment]
Broken dependency has been fixed and v0.3.1 has been released. 

Thanks for reporting!
